/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'secondary-fixed': '#116F6B',
        'surface-variant': '#e5e2db',
        'on-surface': '#1c1c18',
        'outline-variant': '#bfc8c7',
        'on-primary-fixed': '#00201f',
        'surface-tint': '#F7C869',
        'secondary-container': '#0D5653',
        'tertiary-container': '#0A4543',
        'secondary-fixed-dim': '#0D5653',
        'surface-dim': '#dcdad3',
        'on-surface-variant': '#3f4948',
        'surface-container-high': '#ebe8e1',
        'tertiary-fixed-dim': '#8BC4C0',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#0A4543',
        outline: '#707978',
        'surface-container-highest': '#e5e2db',
        'on-tertiary-container': '#8BC4C0',
        'surface-container': '#f0eee7',
        'on-primary-container': '#3D3200',
        'on-primary-fixed-variant': '#0A4543',
        secondary: '#3D3200',
        'on-secondary-container': '#3D3200',
        'on-secondary': '#ffffff',
        'inverse-primary': '#8BC4C0',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#8BC4C0',
        'tertiary-fixed': '#E8F5F4',
        'inverse-on-surface': '#f3f0ea',
        'primary-container': '#F2CA79',
        background: '#fcf9f2',
        'on-secondary-fixed': '#ffffff',
        'surface-bright': '#fcf9f2',
        'on-secondary-fixed-variant': '#0A4543',
        'inverse-surface': '#31312c',
        'on-primary': '#3D3200',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#00201f',
        'surface-container-low': '#f6f3ec',
        'primary-fixed': '#b1eeea',
        tertiary: '#0D5653',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1c18',
        surface: '#fcf9f2',
        primary: '#F7C869',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        'stack-md': '16px',
        'stack-lg': '32px',
        'section-padding': '80px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Playfair Display'],
        'label-md': ['Plus Jakarta Sans'],
        'headline-sm': ['Playfair Display'],
        'body-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Playfair Display'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Playfair Display'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
